### ISSUE TITLE
Blog Posts can pull in Author information from a separate repository

### ISSUE THREAD

**Issue by evantahler** [grouparoo/www.grouparoo.com#18]
Now that we are going to have external contributors, blog posts should load Author information from a fixed location (a JSON file to start).  This information can be displayed at the bottom or side of every post, and on their author page. 

We'll need the following for each author:
- Description (markdown)
- Photo
- URL

**Comment by NotWoods** [comment]
I'll put my speaker bio here for now and tweak it based on everyone else's bios 

> An enthusiastic member of the World Wide Web Consortium, Tiger Oakes loves Progressive Web Apps. After growing up with dead zones in Hawaii, Tiger wants to make web apps that work offline and load fast. He will be working on Microsoft Edge next year. He has previously worked on PWA support in Firefox for Android, web projects for Google Chrome and Yelp, and studies at the University of British Columbia. In his spare time, Tiger searches for geocaches with his partner.
