### ISSUE TITLE
good first issue to be added

### ISSUE THREAD

**Issue by Virajj28** [grouparoo/www.grouparoo.com#723]
As a beginner I want to contribute but couldn't find any good first issue label kindly anyone help me with it.

**Comment by evantahler** [comment]
Hi @Virajj28!  Check out https://www.grouparoo.com/hacktoberfest.  

We don't have any specific issues in this repo yet, but we are looking for help improving our documentation and specifically the first-time setup experience described on pages like these:
* https://www.grouparoo.com/docs/getting-started
* https://www.grouparoo.com/docs/installation
* https://www.grouparoo.com/docs/getting-started/product-concepts

Thanks!
